trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Continuious Integration"
    jobs:
      - job: job01
        displayName: "My CI"
        steps:
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'oscarllamas6'
            displayName: "Artifacts Auth"

          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
            displayName: "Compile"

          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'deploy'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
            displayName: "Publish to Azure DevOps Artifacts"
            

          - task: CopyFiles@2
            inputs:
              Contents: 'target/*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: "Copy artifacts"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'artifact'
              publishLocation: 'Container'
            displayName: "Publish artifacts"